### ISSUE TITLE
Shorten/optimze/refactor getMetricValues.js

### ISSUE THREAD

**Issue by vlabs** [danielbartsch/Challenge01#12]
https://github.com/danielbartsch/Challenge01/blob/develop/utils/getMetricValues.js

**Comment by vlabs** [comment]
with lessons learned from chapter 1 to 4 from https://drboolean.gitbooks.io/mostly-adequate-guide/content/

**Comment by danielbartsch** [comment]
I do not understand what could possibly be easier with curried functions.
I put separate functions for every step in the original getMetricValues function.
https://github.com/danielbartsch/Challenge01/blob/develop/utils/getMetricValues.js
